### ISSUE TITLE
Missing copyright statement

### ISSUE THREAD

**Issue by delorenzo** [infinum/Android-Prince-of-Versions#101]
I don't see a copyright statement (Copyright (c) <date> <copyright holder>) in either the README file or the LICENSE file (also, that file is spelled LICENCE - is that intentional)?  This is needed to give proper attributions for OSS usage.

**Comment by antunflas** [comment]
Hi @delorenzo ,

I've added the copyright into the README file and renamed LICENSE file.

Could you please check if that fit your needs?

**Comment by delorenzo** [comment]
Yes that is perfect, thank you!  I'll mark this as closed.
