### ISSUE TITLE
Discrepancy in comment

### ISSUE THREAD

**Issue by markusi7** [infinum/Android-Prince-of-Versions#29]
In example app:
``` /*  create new instance of updater associated with application context   */```.
The next line is:
```updater = new PrinceOfVersions(this);```, providing the current Activity context.

**Comment by reisub** [comment]
We should have `PrinceOfVersions` call `getApplicationContext()` on the context it receives before using it. That way we eliminate potential memory leaks here.

**Comment by reisub** [comment]
This one is fixed in 2.0.1.
