### ISSUE TITLE
Cert pinning

### ISSUE THREAD

**Issue by kjurkovic** [infinum/Android-Prince-of-Versions#36]
On some projects there is a need to pin the cert due to security reasons. 
It would be nice feature to expose methods for cert pinning.

**Comment by abaotic** [comment]
Devil's advocate here - no, it actually wouldn't.
If the whole API is under a pinned cert, and the POV too, then changing the cert would also break the POV. 
Please reconsider.

**Comment by abaotic** [comment]
Additionally, I would find that updating the application due to POV cert expiration absolutely unacceptable.

**Comment by kjurkovic** [comment]
That is correct but feature would still be useful for testing purposes - most of staging APIs are under self signed certs and POV won't work in those cases

**Comment by abaotic** [comment]
POV should not refer to the same API origin to begin with, because of reasons above.
I understand your test case, but it should be void to begin with.

**Comment by kjurkovic** [comment]
Closing this one - reasons @abaotic stated are valid
