### ISSUE TITLE
Support for declaring minSdk of the latest/minimum version

### ISSUE THREAD

**Issue by reisub** [infinum/Android-Prince-of-Versions#37]
Right now if you upload a new update to play store which raises the minSdk, users below the minSdk will get a notification that there is a new update - however there is no update available for them.

cc @kjurkovic @ikocijan

**Comment by reisub** [comment]
@skliba please take care of this. The new json should look like this:

```
{
    "android": {
        "minimum_version": "1.2.3",
        "minimum_version_min_sdk": 15,
        "latest_version": {
            "version": "2.4.5",
            "notification_type": "ONCE",
            "min_sdk": 16
        }
    }
}
```

The new properties are optional.

Make sure you write tests for it.

**Comment by skliba** [comment]
👍
