### ISSUE TITLE
Do not notify about an update if the version is equal to optional

### ISSUE THREAD

**Issue by ikocijan** [infinum/Android-Prince-of-Versions#40]
A comment from @antunflas :

We have to check if version.isCurrentLessThanOptional() is true, we don't want to notify user about update if he already has equal version to optional.

Probably optional version less than minimum is not valid use case, but it would be better if we don't assume anything about config file maintained by client.

**Comment by skliba** [comment]
I've made a PR of this issue. If you think its okay please close the issues and merge the PR.
