### ISSUE TITLE
Checking for updates even if one of versions is invalid

### ISSUE THREAD

**Issue by antunflas** [infinum/Android-Prince-of-Versions#49]
Currently if you set invalid version for either mandatory or optional version then checking for updates notifies that version is not valid so updater cannot check if there is update or not. But looks like it could be a bit smarter. Sometimes isn't really important to have both valid versions, even one valid version can be enough to notify an update if it exists.

Here are examples (application version is `2.0.0`):
 1. mandatory update is `3.0.0`, while optional update is `3.1` - currently this results as an error because we have optional update that is present, but invalid. However, we'd probably want to get mandatory update notification here.
 2. optional update is `3.1.0`, while mandatory update is `3.0` - this also results as an error, but we can do better. Application has optional update in this case, that's why we can notify it. We don't know anything about mandatory update in this case, but notifying optional update instead of mandatory is still better than notifying only error (ie. notifying nothing).

Of course, if both versions are invalid then we cannot check anything - notifying error is only solution in that case.

**Comment by antunflas** [comment]
@infinum/android-team how does it sound to you? Do you see any problem with this approach?

**Comment by ikocijan** [comment]
@antunflas your explanation looks good. I think we can handle it the way you described.

**Comment by reisub** [comment]
The only problem I see here is that this could be hiding a problem in the config file.
For instance we could have a problem for the mandatory version part and we would not have a way to detect it.

If we always throw an error, we can log it as a handled exception to Fabric for instance and detect that we have a problem in the config file.

I would rather keep the approach we currently use and call the error method if there is a problem in parsing the config file. I'd love to think what the rest of the team thinks, especially people who currently use the library in production.

@kjurkovic @ikocijan @Aksi0m @jmarkovic @markusi7 @zplesac 
I'm not sure who uses it in production, just add people of you know anyone else using it in production.

**Comment by KCeh** [comment]
This issue is not applicable anymore. 
Prince of Versions 4.0.0+ uses different format of versions (version code, ex. 40 instead of 3.0.1 format).
