### ISSUE TITLE
Add synchronous method for update check and pass Throwable in onError

### ISSUE THREAD

**Issue by antunflas** [infinum/Android-Prince-of-Versions#50]
As we'd like to add method for synchronous update check, we need to do some refactoring:
 1. currently we have `VersionVerifier` class which contains all logic for update check. That class also contains logic on which thread is executed that check. I suggest we should split those two things for easier modifications. We'd still have `VersionVerifier` class, but it will contain only update check logic.
 2. as we want to add 2nd method with only different thread, I think it would be better if all update logic (`VersionVerifier` and interactor) is executed synchronously on one thread. We would move threading then to presenter class.
 3. there should still be option to inject the thread so we probably want some type of `ThreadRunner` on which we will run the job.
 4. I'm not sure how clean is to have that runner injected in constructor as it currently is (by injecting `VersionVerifier`) because if we have synchronous method that explicitly use own thread maybe it makes more sense to move that thread definition to asynchronous method.
 5. Error handling isn't the best right now, probably it would make much more sense to pass `Throwable` into `onError` callback than int code of error as it is right now.

@reisub @ikocijan @kjurkovic @jmarkovic @Aksi0m what do you think about it?

**Comment by reisub** [comment]
This sounds good, it will make Prince of Versions easier to use with RxJava.

**Comment by antunflas** [comment]
Done in #54.
