### ISSUE TITLE
Wrong error code for malformed JSON

### ISSUE THREAD

**Issue by zplesac** [infinum/Android-Prince-of-Versions#53]
If by some mistake we receive malformed JSON (let say we've received HTML page :) ), PoV returns WRONG_VERSION error, which is not correct.

We should get something like MALFORMED_JSON error.

**Comment by antunflas** [comment]
This will be solved as part (5th point) of #50. Error method will get Throwable instead of ErrorCode.

**Comment by zplesac** [comment]
Awesome. 

I think that we can close this in favour of #50?

**Comment by antunflas** [comment]
Implemented in #54.
