### ISSUE TITLE
Is there an option to force user to update?

### ISSUE THREAD

**Issue by cliren** [infinum/Android-Prince-of-Versions#58]
Thanks for making this library available in both platforms, can't wait to try it out! I didn't see any option to force update an app, is there a way to achieve this in both platforms?

here is my use case:

- Version 1.0 has a security issue
- Version 1.1 has a fix the security issue
- We would like all users to stop using Version 1.0  and force update them to Version 1.1 when they next use the app.

**Comment by igotepava** [comment]
Hello @cliren!

Making version 1.1.0 a mandatory update is easy! In your JSON file you just set the `minimum_version` to 1.1.0.

When the app with version 1.0.0 checks for updates, the `UpdaterCallback`'s method `onNewUpdate(String version, boolean isMandatory, Map<String, String> metadata)` will be called. The parameter `isMandatory` will be `true`. Here, it's up to you how you will handle the mandatory update (e.g. not letting the user do anymore interactions until the app is updated).

Hope this helps.

**Comment by cliren** [comment]
thanks!
