### ISSUE TITLE
Optional update not triggered

### ISSUE THREAD

**Issue by deankostomaj** [infinum/Android-Prince-of-Versions#61]
I think that bug is line 51 of PovInteractorImpl.java file because that is way optional update is not triggered.

I had my versions like:

- version: 2.0.0
- min version: 1.0.1
- SDK: 26
- min SDK: 19

Versions on phone:
- version: 1.2.1
- SDK: 23

Either getNewMinSdk() method should return minimum required min SDK or last condition should be removed. In my case version on phone was lower than newest version (2.0.0 > 1.2.1) but newMinSdk was not smaller or equal to sdk on phone (26 <= 23 is false).

I solved my issue with using 2.0.3 version. Now it works as expected.

**Comment by antunflas** [comment]
Hello @deankostomaj 

Can you confirm that you're configuration is same as the following snippet?
```
"android": {
    "minimum_version": "1.0.1",
    "minimum_version_min_sdk": 19,
    "latest_version": {
        "version": "2.0.0",
        "min_sdk":26
    }
}
```

If that's correct then you won't get an update because min_sdk version of latest version is greater than the device supports.

If version 2.0.0 has minSdk set to 26, then you can't install the update on the phone that has Android version 23.

Is it maybe a case that you set minSdk value to value of targetSdk, because 26 seems a bit high for a minSdk at the moment.

**Comment by deankostomaj** [comment]
Ohh I see. So both minimum_version_min_sdk and min_sdk should be set to 19 if I want to run my app on 19 and above. What is the difference between those two then?

By the way, yes that is the structure of my JSON on server.

**Comment by deankostomaj** [comment]
Never mind. Stupid question I figured it out. :D Thanks anyway.

**Comment by antunflas** [comment]
That's correct.
The difference is that `minimum_version_min_sdk` applies for `minimum_version`, ie. for mandatory version, while `min_sdk ` applies for `latest_version`, ie. for optional update.

For example, if you have minimum version of your app 1.0.1 that supports sdk >= 19 you would have settings you have for `minimum_version`. However, if you release the update which is build just for sdk >= 21 you would set latest versions's `min_sdk` to 21 to only users with sdk 21 and greater would be able to update the app to that version.

**Comment by deankostomaj** [comment]
Thank you for your help and kindness.
