### ISSUE TITLE
Failed to resolve: co

### ISSUE THREAD

**Issue by robersom** [infinum/Android-Prince-of-Versions#63]
in build.gradle app

- compileSdkVersion 27
- minSdkVersion 15

dependencies {
    ...
    implementation 'co.infinum:prince-of-versions:latest_version'
    ...
}
Failed to resolve: co

**Comment by reisub** [comment]
@robersom you probably already figured this out, but just for reference - you need to change `latest_version` to the actual latest version - which is 2.1.0 right now.
