### ISSUE TITLE
Several suggestions to improve library

### ISSUE THREAD

**Issue by domagojkorman** [infinum/Android-Prince-of-Versions#64]

**Comment by domagojkorman** [comment]
Ignore the fail, when I pressed enter it automatically opened the issue :D

1) Builder pattern when creating Prince of versions instance
2) Separate interface that is consumed by the user from the implementation
3) Add nullable and non null annotations to the interface to make it clear which value I can expect
4) Improve README because some parts are not clear enough, e.g. it is not explained what happens if notification_type is ALWAYS and update is mandatory which can lead to confusion

**Comment by antunflas** [comment]
> - [x] Builder pattern when creating Prince of versions instance
> - [ ] ~Separate interface that is consumed by the user from the implementation~
> - [x] Add nullable and non null annotations to the interface to make it clear which value I can expect
> - [x] Improve README because some parts are not clear enough, e.g. it is not explained what happens if notification_type is ALWAYS and update is mandatory which can lead to confusion

Done everything except 2nd point.
If interface is needed, library user can wrap the `PrinceOfVersions` with his custom interface implementation. Let's leave it like this for now.
