### ISSUE TITLE
Error while trying to read the json

### ISSUE THREAD

**Issue by kwafoawua** [infinum/Android-Prince-of-Versions#70]
Hello!
I'm having trouble with trying to read the json. I just copypasted the README code and part of the CommonUsageExample just to see if I can get a Log of the returning info but I always get this error.
`Unexpected character 'DOT(.)' at position '5', expecting '[HYPHEN, PLUS, EOI]'`

The JSON I'm using is the same as in the examples as well, since I'm just trying to make it work first. 

Prince-of-Versions: 3.0.0

I hope someone can guide me.

Thanks

**Comment by antunflas** [comment]
Hello @kwafoawua,

what is the version name of your app?
It should follow semantic versioning standard: https://semver.org/

**Comment by kwafoawua** [comment]
The version name of my app is 2.8.0.0 . I changed it to 2.8.0 and it's working as expected!
Thank you very much!
I'll close this.
