### ISSUE TITLE
Unexpected character 'EOI(null)' at position '3', expecting '[DOT]

### ISSUE THREAD

**Issue by timi-codes** [infinum/Android-Prince-of-Versions#71]
Below is the json i'm passing. Same thing happening locally
`{
    "ios": {
        "minimum_version": "1.2.3",
        "latest_version": {
            "version": "2.4.5",
            "notification_type": "ALWAYS"
        }
    },
    "android": {
        "minimum_version": "1.2.3",
        "latest_version": {
            "version": "2.4.5",
            "notification_type": "ONCE"
        }
    }
}`

**Comment by antunflas** [comment]
Hello,

is the application version name in format `major.minor`?
The library expects all versions according to Semantic versioning standard, so please use `major.minor.patch` for application version name.

**Comment by timi-codes** [comment]
Thanks. it worked
